version: '3'
services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    image: ttl.sh/bernhack-web
    build: ./
    ports:
      - "8000"
    depends_on:
      - postgres


networks:
  web:
    external: true
