site_name: medical-receipt
site_description: Backend for Medical receipt app
repo_url: https://github.com/bernhack-medical-receipt/bernhack-medical-receipt
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/bernhack-medical-receipt">bernhack-medical-receipt</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
