# Generated by Django 4.1 on 2022-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('USER', 'User'), ('DOC', 'Doctor'), ('PHAR', 'Pharmacist')], default='USER', max_length=4),
        ),
    ]
