# Generated by Django 4.1 on 2022-08-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
