# Generated by Django 4.1 on 2022-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_receipt_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="active_ingredients",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drug",
            name="application",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drug",
            name="category",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drug",
            name="ingredients",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drug",
            name="license_owner",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drug",
            name="package_size",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drug",
            name="unit",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
