# Generated by Django 4.1 on 2022-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_drug_active_ingredients_drug_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='active_ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='application',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='license_owner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='package_size',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='unit',
            field=models.TextField(),
        ),
    ]
